exec-once = hyprpaper
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = swaync
exec-once = qs -c noctalia-shell
exec-once = kitty
exec-once = brave
exec-once = spotify
exec-once = obsidian
exec-once = virt-manager
